name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/Checkout@v3
        with:
          fetch-depth: 0

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v4.0.3
        with:
          major_pattern: "major:"
          minor_pattern: "feat:"
          format: "${major}.${minor}.${patch}-prerelease${increment}"
        id: version
          
      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          echo $NEW_VERSION

      # - name: Build docker image
      #   env:
      #     NEW_VERSION: ${{ steps.version.outputs.version }}
      #   run: |
      #     docker build -t joeldevnet/docker-graphql:$NEW_VERSION .
      #     docker build -t joeldevnet/docker-graphql:latest .

      # - name: Push docker image
      #   env:
      #     NEW_VERSION: ${{ steps.version.outputs.version }}
      #   run: |
      #     docker push joeldevnet/docker-graphql:$NEW_VERSION
      #     docker push joeldevnet/docker-graphql:latest

